### ISSUE TITLE
About the dtu_sparse

### ISSUE THREAD

**Issue by Xiangbwen** [l1346792580123/PatchShading#1]
How do I get the PKL file of my own dataset?

**Comment by l1346792580123** [comment]
We use [colmap](https://github.com/colmap/colmap) to perform sparse reconstruction and save the results in pkl format. You can refer to the colmap's [documentation](https://colmap.github.io) for sparse reconstruction and convert [points3D.txt](https://colmap.github.io/format.html#points3d-txt) to pkl format.
