### ISSUE TITLE
How to get the pair .txt file？

### ISSUE THREAD

**Issue by Xiangbwen** [l1346792580123/PatchShading#2]
I used colmap2mvsnet.py to convert the data I got from colmap to the format of the pair.txt. But the results obtained by ncc_optim.py are not good.
sp:
![微信截图_20240110165904](https://github.com/l1346792580123/FastHuman/assets/141302981/d95e2d06-c991-4251-a48f-6f632d07e995)
ncc:
![微信截图_20240110165936](https://github.com/l1346792580123/FastHuman/assets/141302981/f304a645-7c83-4669-9347-933f9367e770)

**Comment by l1346792580123** [comment]
pairs.txt is pre-artificially defined. The format of our pairs.txt is not quite the same as the format that colmap2mvsnet.py get. Our pairs.txt only contain the reference image id and source image id.

**Comment by Xiangbwen** [comment]
> pairs.txt is pre-artificially defined. The format of our pairs.txt is not quite the same as the format that colmap2mvsnet.py get. Our pairs.txt only contain the reference image id and source image id.

I get it. Thank you for your reply.
