### ISSUE TITLE
points.pkl has no key uvs

### ISSUE THREAD

**Issue by ansj11** [l1346792580123/PatchShading#3]
I am using my colmap dataset to run the ncc_optim.py, and convert points3D.bin to points.pkl, but I find that img_points has no keys named uvs. Why?

<img width="920" alt="截屏2024-05-13 16 18 23" src="https://github.com/l1346792580123/FastHuman/assets/24786133/54def3ce-8e9e-42aa-94d7-241a937bdf76">

**Comment by l1346792580123** [comment]
uvs represent the corresponding image coordinates of 3D points, you need load images.bin and convert the POINT2D_IDX in points3D.bin to image coordinates.

**Comment by ansj11** [comment]
thank you for your quick response. I don't know how to change colmap data format to get points.pkl and pair.txt, could you provide me a preprocessing script?
