### ISSUE TITLE
eglInitialize() failed

### ISSUE THREAD

**Issue by ansj11** [l1346792580123/PatchShading#4]
hi~, I got the following error, do you know the reason?

[F glutil.cpp:338] eglInitialize() failed
run.sh: line 2:  4771 Aborted                 (core dumped) python ncc_optim.py --conf confs/nhr_ncc.conf --scan_id 10

**Comment by l1346792580123** [comment]
please follow this [issue](https://github.com/NVlabs/nvdiffrast/issues/58) or use dr.RasterizeCudaContext to replace dr.RasterizeGLContext instead.

**Comment by ansj11** [comment]
thanks for your reply! I have solved this problem.
