### ISSUE TITLE
How change camera pose to NeuS

### ISSUE THREAD

**Issue by ansj11** [l1346792580123/PatchShading#5]
I want to train Neus with NHR dataset, but I don't know the coordinate system. Do you know how I can do?

**Comment by l1346792580123** [comment]
Here is the [example script](https://github.com/l1346792580123/FastHuman/files/15425566/nhr_convert.zip) to convert NHR dataset to NeuS format. You can replace the mesh with the point cloud provided by NHR dataset to calculate the centroid.

**Comment by ansj11** [comment]
thank you for your rely!
