### ISSUE TITLE
Abnormal mesh with custom data

### ISSUE THREAD

**Issue by ansj11** [l1346792580123/PatchShading#7]
I have 500 images from iPhone with colmap camera pose, and I use colmap2mvsnet.py to get pair.txt and points.pkl, but the optimized mesh looks not good. Do you know why? 

Uploading 屏幕录制2024-05-31 10.38.17.mov…

**Comment by l1346792580123** [comment]
I can't see the uploaded video.

**Comment by ansj11** [comment]
sorry, the video maybe too big to upload, I only upload 2 screenshots.
<img width="429" alt="截屏2024-06-04 10 35 22" src="https://github.com/l1346792580123/FastHuman/assets/24786133/bc3f546a-f7ca-4be0-9abc-14d3d819e0e3">
<img width="347" alt="截屏2024-06-04 10 35 29" src="https://github.com/l1346792580123/FastHuman/assets/24786133/38f0d056-f9de-48a5-b710-8379cd3aa745">

**Comment by l1346792580123** [comment]
You can change the sig and lap_weight to get a smooth mesh. There is no need to use all the images for reconstruction, and the varying lighting can affect the results. you can select like 20 images for reconstruction and ignore those images where the person is completely sideways.

**Comment by ansj11** [comment]
thank you for your response! I will have a try!
